copy C:\Work\git\Reify\NNP\src\com\sackett\reify\nn\*.java "C:\Users\user1\Google Drive\School\Courses\NeuralNetworks-578\FinalProject\source"
copy C:\Work\git\Reify\NNP\*.txt "C:\Users\user1\Google Drive\School\Courses\NeuralNetworks-578\FinalProject\source"
copy C:\Work\git\Reify\NNP\*.html "C:\Users\user1\Google Drive\School\Courses\NeuralNetworks-578\FinalProject\source"
copy C:\Work\git\Reify\NNP\*.bat "C:\Users\user1\Google Drive\School\Courses\NeuralNetworks-578\FinalProject\source"
copy C:\Work\git\Reify\NNP\*.csv "C:\Users\user1\Google Drive\School\Courses\NeuralNetworks-578\FinalProject\source"
