copy C:\Users\Joe\git\Reify\BP\src\com\sackett\reify\bp\*.java "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\src\com\sackett\reify\bp\view\*.java "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\*.txt "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\*.html "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\*.bat "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\*.csv "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
copy C:\Users\Joe\git\Reify\BP\*.docx "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Project\source"
